platform: Sumologic Query
source: windows_smbclient-security
description: Text that describe current mapping

log_source:
  _sourceCategory: [windows]

default_log_source:
  _sourceCategory: windows

field_mapping:
  EventID: EventID
